apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slurm-controller
spec:
  serviceName: slurm-controller
  replicas: 1
  selector:
    matchLabels:
      app: slurm-controller
      component: controller
  template:
    metadata:
      labels:
        app: slurm-controller
        component: controller
    spec:
      dnsConfig:
        searches:
          - slurm-controller.tsisodia.svc.cluster.local
          - slurm-node.tsisodia.svc.cluster.local
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: true
        capabilities:
          add: ["SYS_ADMIN"]
      containers:
      - name: slurm-controller
        image: {{ .Values.slurm.controller.image }}
        volumeMounts:
        - name: slurm-config
          mountPath: /etc/slurm-llnl/slurm.conf
          subPath: slurm.conf
        - name: slurm-state
          mountPath: /var/spool   # Mounting the state volume here
        - mountPath: /run/munge
          name: munge-socket 
        - name: munge-key-volume
          mountPath: /etc/munge/munge.key
          subPath: munge.key
          readOnly: true    
      volumes:
      - name: slurm-config
        configMap:
          name: slurm-config  
      - name: munge-socket
        emptyDir: {}    
      - name: munge-key-volume
        secret:
          secretName: munge-key-1     
  volumeClaimTemplates:
  - metadata:
      name: slurm-state
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
