apiVersion: v1
kind: Service
metadata:
  name: slurm-controller
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6817 
      protocol: TCP
      name: slurm-ctl
  selector:
    app: slurm
    component: controller
