apiVersion: v1
kind: Service
metadata:
  name: slurm-controller-headless
spec:
  clusterIP: None  # This makes it a headless service
  selector:
    app: slurm-controller
  ports:
    - protocol: TCP
      port: 6817
      targetPort: 6817
