apiVersion: v1
kind: Service
metadata:
  name: slurm-node-headless
spec:
  clusterIP: None  # Use clusterIP: None for a headless service
  ports:
    - port: 6818
      targetPort: 6818
      protocol: TCP
      name: slurm-node
  selector:
    app: slurm
    component: node
