apiVersion: v1
kind: Service
metadata:
  name: slurm-node
spec:
  clusterIP: None
  ports:
    - port: 6818
      targetPort: 6818
      protocol: TCP
      name: slurm-node
  selector:
    app: slurm
    component: node
