apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slurm-node
spec:
  serviceName: "slurm-node-headless"
  replicas: 4
  selector:
    matchLabels:
      app: slurm
      component: node
  template:
    metadata:
      labels:
        app: slurm
        component: node
    spec:
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: true
        capabilities:
          add: ["SYS_ADMIN"]
      containers:
      - name: slurm-node
        image: quay.io/tsisodia10/slurm-node:0.11  # Replace with your SLURM node image
        volumeMounts:
        - name: slurm-node-config
          mountPath: /etc/slurm-llnl/slurm.conf
          subPath: slurm.conf
      volumes:
      - name: slurm-node-config
        configMap:
          name: slurm-config
  volumeClaimTemplates:
  - metadata:
      name: slurm-node-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
